version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092

  redis:
    image: redis:6
    ports:
      - '6380:6379' # Changed host port to 6380

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
